catshef/cart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cart import views

urlpatterns = [
    url(r'^add/$', views.add_to_cart, name='cart_add'),
    url(r'^remove/$', views.remove_from_cart, name='cart_remove'),
    url(r'^clear/$', views.clear_cart, name='cart_clear'),
]

catshef/catshef/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('products.urls', namespace='products')),
]

catshef/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^product/(?P<slug>[\w-]+)/$',
        views.product_detail, name='product_detail'),
    url(r'^product/related/(?P<slug>[\w-]+)/$', views.product_related,name='product_related'),
    url(r'^category/(?P<slug>[\w-]+)/$', views.category, name='category'),
]

catshef/products/models.py
import decimal

from products.utils.conversion import round_decimal

from django.db import models
from django.db.models import Count
import django.core.exceptions as exceptions

from django.core.urlresolvers import reverse

from products.utils.nutrition import CAL2000    

class AvailableManager(models.Manager):
    """
    Used to query only for available products.
    """
    def get_queryset(self):
        return super(AvailableManager, self).get_queryset().filter(available=True)

class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField()
    description = models.TextField()
    parent = models.ForeignKey('Category', null=True, 
        related_name='child_categories', on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return reverse('products:category', kwargs={'slug':self.slug})

    def __str__(self):
        return self.name

class Product(models.Model):
    """
    Represents a product that's being sold.
    """
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, db_index=True)
    description = models.TextField()
    categories = models.ManyToManyField('Category', related_name='products')
    stock = models.PositiveSmallIntegerField()  # range: [0, 32767]
    price = models.DecimalField(max_digits=10, decimal_places=2)
    offer_price = models.DecimalField(max_digits=10, 
                                         decimal_places=2, null=True)
    # TODO: set default image (replace null=True) or just use default image
    # in template rendering (decide)
    main_image = models.ForeignKey('ProductImage', 
        related_name='main_image_of', null=True, on_delete=models.SET_NULL)
    nutrition = models.ForeignKey('ProductNutrition', 
        on_delete=models.SET_NULL, null=True, blank=True)
    ingridients = models.ManyToManyField('Ingridient', related_name='products')
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()  # default manager
    active = AvailableManager() 

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'slug': self.slug})

    def get_all_images(self):
        """
        Get all images, including the 'main_image', if present.

        Returns an empty list if no images are found.
        """
        if not self.images:
            return []

        images = self.images.all()
        return images

    def get_images(self):
        """
        Get all images, except the 'main_image', if present.

        Return an empty list if no images are found.
        """
        images = self.get_all_images()
        return images.exclude(pk=self.main_image.pk) if self.main_image else images

    def get_all_images_urls(self):
        """
        Get all images urls, including the 'main_image', if present.

        Returns an empty list if no images are found.
        """
        return [image.image.url for image in self.get_all_images()]

    def get_images_urls(self):
        """
        Get all images urçs, except the 'main_image', if present.

        Return an empty list if no images are found.
        """
        return [image.image.url for image in self.get_images()]

    def get_default_options(self):
        options = []
        groups = self.groups.all()
        for group in groups:
            # get all memberships with that group that are "default"
            memberships = Membership.objects.filter(group=group, default=True)
            for m in memberships:
                options.append(m.option)
        return options

    def similar_products(self, manager=None, limit=None):
        if not manager:
            manager = Product.active

        category_ids = self.categories.values_list('id', flat=True)
        similar_posts = manager.filter(categories__in=category_ids).exclude(pk=self.pk)
        similar_posts = similar_posts.annotate(
            same_categories=Count('categories')).order_by('-same_categories', '-updated')
        
        if limit:
            similar_posts = similar_posts[:limit]
        return similar_posts

    def __str__(self):
        return self.name

    @property
    def main_image_url(self):
        """
        Shorthand for the main image url
        """
        if not self.main_image:
            return None
        return self.main_image.image.url


    @property
    def current_price(self):
        """
        If there is an 'offer_price' set and it's less than 'price',
        'product.current_price' will return 'product.offer_price', 
        otherwise product.price will be returned.

        This should make the price access in templates and order price 
        computation less verbose (basically avoiding many if's, which can cause 
        bugs, if it's ommited in some place by mistake).
        """
        if self.has_offer:
            return self.offer_price
        return self.price

    @property
    def discount_percentage(self):
        """
        Get the discount as a percentage. 

        Note: if offer_price >= price, 0 will be returned
        """
        if self.has_offer:
            return 100 - (self.offer_price * 100 / self.price)

    @discount_percentage.setter
    def discount_percentage(self, percent):
        """
        Set the 'offer_price' as a percentage of the 'price'.

        Args:
            precent (int): how much percent to discount. A percentual value has 
            to be passed. For example, if you want the discount to be of 30%, 
            youcwould write: 'product.discount_percentage=30'.
        """
        self.offer_price = self.price * (100 - percent)/100

    @property
    def has_offer(self):
        """
        Returns True if the product has a valid offer price and False
        otherwise.
        """
        return self.offer_price and self.offer_price < self.price

    @property
    def protein(self):
        if not self.nutrition:
            return None
        return self.nutrition.protein

    @property
    def carbs(self):
        if not self.nutrition:
            return None
        return self.nutrition.carbs

    @property
    def fat(self):
        if not self.nutrition:
            return None
        return self.nutrition.fat

    @property
    def calories(self):
        if not self.nutrition:
            return None
        return self.nutrition.calories

    @property
    def nutrition_dict(self):
        if not self.nutrition:
            return None
        return {'protein': self.nutrition.protein, 
                'carbs': self.nutrition.carbs,
                'fat': self.nutrition.fat,
                'calories': self.nutrition.calories,
                }

    @property
    def has_nutrition(self):
        return self.nutrition is not None

    @property
    def protein_daily_percent(self, nutr_info=CAL2000, round=True):
        if self.has_nutrition:
            res = self.protein*100/nutr_info.protein
            return self.__round(res, round)
        return 0
    
    @property
    def carbs_daily_percent(self, nutr_info=CAL2000, round=True):
        if self.has_nutrition:
            res = self.carbs*100/nutr_info.carbs
            return self.__round(res, round)
        return 0
    
    @property
    def fat_daily_percent(self, nutr_info=CAL2000, round=True):
        if self.has_nutrition:
            res = self.fat*100/nutr_info.fat
            return self.__round(res, round)
        return 0

    def __round(self, value, round=True):
        return float('{0:.1f}'.format(value)) if round else value

        
    

class ProductImage(models.Model):
    # image will be uploaded to MEDIA_ROOT/products/%Y/%m/%d/
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    product = models.ForeignKey('Product', related_name='images')
    # TODO: Order field

class ProductNutrition(models.Model):
    __PROT_CAL = __CARB_CAL = 4
    __FAT_CAL = 9

    protein = models.DecimalField(max_digits=10, decimal_places=1)
    carbs = models.DecimalField(max_digits=10, decimal_places=1)
    fat = models.DecimalField(max_digits=10, decimal_places=1)
    calories = models.DecimalField(max_digits=10, decimal_places=1, null=True, 
        blank=True)

    def save(self, *args, **kwargs):
        if self.calories is None:
            self.calories = type(self).__PROT_CAL * self.protein + type(self).__CARB_CAL * self.carbs + type(self).__FAT_CAL * self.fat
        super(ProductNutrition, self).save(*args, **kwargs)

class Ingridient(models.Model):
    # NOTE: the imaage will be displayed with size 80x80, so use somethimg 
    # that scales well
    name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='ingridients/%Y/%m/%d/')

    def __str__(self):
        return self.name

class Membership(models.Model):
    """
    Through model for ProductOptionGroup to ProductOption many-to-many
    relationship.

    Fields:
        default (BooelanField): if True, this option is selected by default
    """
    group = models.ForeignKey('ProductOptionGroup', on_delete=models.CASCADE)
    option = models.ForeignKey('ProductOption',
        related_name='membership', on_delete=models.CASCADE)
    default = models.BooleanField(default=False, blank=True)

    def clean(self):
        if self.group.type in (ProductOptionGroup.RADIO, ProductOptionGroup.DROPDOWN):
            if self.default == True:
                if Membership.objects.filter(group=self.group,
                    default=True).exists():
                    raise exceptions.ValidationError('This group already has '
                        'one field with default set to True.')

    def save(self, *args, **kwargs):
        # NOTE: won't work for bulk object creation, since save() isn't called
        # then, as per Django's docs:

catshef/products/views.py
from django.shortcuts import render
from products.models import Product, Category
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from common.decorators import ajax_required

def index(request):
    products = Product.objects.all()
    return render(request, 'products/index.html', {
        'products': products,
        })

def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    return render(request, 'products/detail.html', {'product': product})

def category(request, slug):
    category = Category.objects.get(slug=slug)
    products = Product.objects.filter(categories=category)
    paginator = Paginator(products, 8)
    page_num = request.GET.get('page')
    try:
        products = paginator.page(page_num)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        products = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'products/list_ajax.html', {'products':products,
            'page_num':page_num})
    return render(request, 'products/category_list.html', {'category':category})

@ajax_required
def product_related(request, slug):
    product = Product.active.get(slug=slug)
    products = product.similar_products()
    paginator = Paginator(products, 8)
    page_num = request.GET.get('page')

    try:
        products = paginator.page(page_num)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        return HttpResponse('')
    return render(request, 'products/list_ajax.html', {'products':products})

catshef/products/templates/products/category_list.html
{% extends "products/base.html" %}

{% block title %}{{ site_name }}-{{ category }}{% endblock title %}

{% block content %}
<div class="content-top ">
    <div class="container ">
    <div id="products-list" class="con-w3l">
        {% include "products/list_ajax.html" %}
    </div>
    </div>
    </div>
{% endblock content %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    function load_products(force_load=false) {
        if (empty_page) {
            return false;
        }
             
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && !empty_page && !block_request || force_load) {
            block_request = true; // prevent other AJAX calls from happening, while this one is active
            $.get('?page=' + page, function(data) {
                if (data == '') {
                    empty_page = true;
                } else {
                    block_request = false;
                    $('#products-list').append(data);
                }
            });
            page += 1;
            return true; // images have been loaded
        }
        return false;
    }

    load_products(true); // force load product list on page load

    /*
        Product loading "hack": If the resolution is hight enough, there will be no scroll bar, therefore no scroll event, so at most X products will be loaded.
        The timer forces the check every second to get arround that problem.
    */

    function handle_timeout() {
        var images_loaded = load_products();
        if (images_loaded) {
            window.setTimeout(handle_timeout, 1000);
        }
        /* 
            if no images have been loaded (images_loaded == false), this means that either:
                1. current window position is not low enough, so that means that the scroll event will fire next time, so
                   we don't need the timeout anymore
                2. no more products are available, so no need to make unneceassary requests
        */
    }
    
    window.setTimeout(handle_timeout, 1000);

    $(window).scroll(load_products);

{% endblock domready %}

catshef/products/templates/products/detail.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block title %}{{ site_name }}| {{ product }}{% endblock title %}
{% block head %}

<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700,800" rel="stylesheet" type="text/css">

<!-- CSS for nutrition table -->
<link rel="stylesheet" type="text/css" href="{% static "css/nutr-table.css" %}">

<!-- Owl Carousel Setup -->
<!-- Important Owl stylesheet -->
<link rel="stylesheet" href="{% static "owl-carousel/owl.carousel.css" %}">
<link rel="stylesheet" href="{% static "css/prod-detail.css" %}">

<!-- Default Theme -->
<link rel="stylesheet" href="{% static "owl-carousel/owl.theme.css" %}">
<link rel="stylesheet" href="{% static "owl-carousel/custom.css" %}">

<!-- Include js plugin -->
<!-- TODO: move this to bottom of the page -->
<script src="{% static "owl-carousel/owl.carousel.js" %}"></script>
<!-- //Owl Carousel Setup -->

{% endblock head %}

{% block content %}

<script type="text/javascript">
    $(document).ready(function() {

      var sync1 = $("#sync1");
      var sync2 = $("#sync2");

      sync1.owlCarousel({
        singleItem : true,
        slideSpeed : 1000,
        navigation: true,
        pagination:false,
        afterAction : syncPosition,
        responsiveRefreshRate : 200,
    });

      sync2.owlCarousel({
        items : 5,
        itemsDesktop      : [1199,3],
        itemsDesktopSmall     : [979,3],
        itemsTablet       : [768,3],
        itemsMobile       : [479,3],
        pagination:false,
        responsiveRefreshRate : 100,
        afterInit : function(el){
          el.find(".owl-item").eq(0).addClass("synced");
      }
  });

      function syncPosition(el){
        var current = this.currentItem;
        $("#sync2")
        .find(".owl-item")
        .removeClass("synced")
        .eq(current)
        .addClass("synced")
        if($("#sync2").data("owlCarousel") !== undefined){
          center(current)
      }
  }

  $("#sync2").on("click", ".owl-item", function(e){
    e.preventDefault();
    var number = $(this).data("owlItem");
    sync1.trigger("owl.goTo",number);
});

  function center(number){
    var sync2visible = sync2.data("owlCarousel").owl.visibleItems;
    var num = number;
    var found = false;
    for(var i in sync2visible){
      if(num === sync2visible[i]){
        var found = true;
    }
}

if(found===false){
  if(num>sync2visible[sync2visible.length-1]){
    sync2.trigger("owl.goTo", num - sync2visible.length+2)
}else{
    if(num - 1 === -1){
      num = 0;
  }
  sync2.trigger("owl.goTo", num);
}
} else if(num === sync2visible[sync2visible.length-1]){
  sync2.trigger("owl.goTo", sync2visible[1])
} else if(num === sync2visible[0]){
  sync2.trigger("owl.goTo", num-1)
}

}

});
</script>


<div class="single">
    <div class="container">
        <div class="single-top-main product-essential">
            <div class="col-md-5 single-top">
                <div class="single-w3agile">

                    <div id="picture-frame">
                        <div id="sync1" class="owl-carousel">
                            {% with product_images_urls=product.get_images_urls main_image_url=product.main_image_url %}
                            {% if not main_image_url %}
                            main_image_url = {% static "images/no_image.jpg" %}
                            {% endif %}

                            <div class="item"><img src="{{ main_image_url }}"></div>

                            {% for image_url in product_images_urls %}
                            <div class="item" image-count="{{ forloop.counter }}"><img src="{{ image_url }}"></div>
                            {% endfor %}
                        </div>
                        <div id="sync2" class="owl-carousel">
                            {% if not main_image_url %}
                            main_image_url = {% static "images/no_image.jpg" %}
                            {% endif %}

                            <div class="item"><img src="{{ main_image_url }}"></div>

                            {% for image_url in product_images_urls  %}
                            <div class="item" image-count="{{ forloop.counter }}"><img src="{{ image_url }}"></div>
                            {% endfor %}
                            {% endwith %}
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-7 single-top-left ">
                <div class="single-right">
                    <h3>{{ product }}</h3>

                    
                    <div class="pr-single">
                      <p class="reduced">
                          {% if product.has_offer %}
                          <del>&euro;{{ product.price }}</del>
                          {% endif %}
                          &euro;{{ product.current_price }}</p>
                      </div>
                      {% with categories=product.categories.all %}
                          {% if categories %}
                              <div class="prod-detail-categories">

                              {% for category in categories %}
                                   <a href="{{ category.get_absolute_url }}" class="category-link"><span class="label label-success">{{ category }}</span></a>    
                              {% endfor %}

                              </div>  
                          {% endif %}
                      {% endwith %}
                      <div class="block block-w3">
                        <div class="starbox small ghosting"> </div>
                    </div>
                    <p class="in-pa"> {{ product.description }} </p>
                    <ul class="social-top">
                        <li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
                        <li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
                        <li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
                        <li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
                    </ul>
                    <div class="add add-3">
                       <button class="btn btn-danger my-cart-btn my-cart-b" data-id="1" data-name="Wheat" data-summary="summary 1" data-price="6.00" data-quantity="1" data-image="images/si.jpg">Add to Cart</button>
                   </div>



                   <div class="clearfix"> </div>
               </div>


           </div>
           <div class="clearfix"> </div>
       </div>   

       <div class="single-top-main">
          <div class="product-collateral">
            <ul id="product-detail-tab" class="nav nav-tabs product-tabs">
              <li class="active"> <a href="#product_tabs_description" data-toggle="tab"> Product Description </a> </li>
              <li class=""><a href="#product_tabs_nutrition" data-toggle="tab">Nutrition</a></li>
          </ul>

          <!-- tab content -->
          <div id="productTabContent" class="tab-content">
              <div class="tab-pane fade active in" id="product_tabs_description">
                <div class="std tab-text">
                    <p>{{ product.description }}</p>
                </div>
            </div>

            <div class="tab-pane fade" id="product_tabs_nutrition">
                {% if product.ingridients %}
                    <div class="row">
                        <div class="col-md-8 col-xs-12">
                            {% include "products/ingridients_list.html" with ingridients=product.ingridients.all %}
                        </div>
                        <div class="col-md-4 col-xs-12">
                            {% include "products/nutrition_table.html" with product=product %}
                        </div>
                    </div>
                {% else %}
                {% comment %}
                    TODO: how to display if no product nutrients are available?
                    See Issue #25: https://github.com/iluxonchik/catshef/issues/25
                {% endcomment %}
                    {% include "products/nutrition_table.html" with product=product %}
                {% endif %}
            </div>
            <!-- //tab content -->

        </div>
    </div>

    <div class="box-additional">
            <!-- BEGIN RELATED PRODUCTS -->
            <div class="related-pro container">
              <div class="slider-items-products">
                <div class="new_title center">
                  <h2>Related Products</h2>
                </div>
                <div id="related-products-list">
                  {% include "products/list_ajax.html" %}
                </div>
              </div>
            </div>
            <!-- end related product -->
            
          </div>
</div>

</div>
</div>
{% endblock content %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    function load_products(force_load=false) {
        if (empty_page) {
            return false;
        }

        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > (margin && !empty_page && !block_request) || force_load) {
            block_request = true; // prevent other AJAX calls from happening, while this one is active
            $.get('/product/related/{{ product.slug }}/?page=' + page, function(data) {
                if (data == '') {
                    empty_page = true;
                } else {
                    block_request = false;
                    $('#related-products-list').append(data);
                }
            });
            page += 1;
            return true; // images have been loaded
        }
        return false;
    }

    load_products(true); // force load product list on page load

    /*
        Product loading "hack": If the resolution is hight enough, there will be no scroll bar, therefore noproducts scroll event, so at most X products will be loaded.
        The timer forces the check every second to get arround that problem.
    */

    function handle_timeout() {
        var images_loaded = load_products();
        if (images_loaded) {
            window.setTimeout(handle_timeout, 1000);
        }
        /* 
            if no images have been loaded (images_loaded == false), this means that either:
                1. current window position is not low enough, so that means that the scroll event will fire next time, so
                   we don't need the timeout anymore
                2. no more products are available, so no need to make unneceassary requests
        */
    }
    
    window.setTimeout(handle_timeout, 1000);

    $(window).scroll(load_products);

{% endblock domready %}

catshef/products/templates/products/login-modal.html
    {% load staticfiles %}
    {% load  html_filters%}
    <!-- Login/Register modal -->
    <div class="modal fade login" id="login-modal">
      <div class="modal-dialog login animated">
        <div class="modal-content">
         <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Login with</h4>
        </div>
        <div class="modal-body">  
          <div class="box">
           <div class="content">
            <div class="social">
              <a id="google_login" class="circle google" href="#">
                <i class="fa fa-google-plus fa-fw"></i>
              </a>
              <a id="facebook_login" class="circle facebook" href="#">
                <i class="fa fa-facebook fa-fw"></i>
              </a>
            </div>
            <div class="division">
              <div class="line l"></div>
              <span>or</span>
              <div class="line r"></div>
            </div>
            <div class="error"></div>
            <div class="form loginBox">

              <form id="modal-login-form" method="post" action="" accept-charset="UTF-8">

              {% for hidden in login_form.hidden_fields %}
                  {{ hidden }}
              {% endfor %}

              {% with field=login_form.login|add_class:'form-control' %}
                {{ field|add_placeholder:'Email' }}
              {% endwith %}

              {% with field=login_form.password|add_class:'form-control' %}
                {{ field|add_placeholder:'Password' }}
              {% endwith %}

              <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="id_remember">
                   <span class="mdl-checkbox__label">Remember me?</span>
                   {{ login_form.remember|add_class:'mdl-checkbox__input' }}
              </label>

              <!--
                <input id="id_email2" class="form-control" type="text" placeholder="Email" name="email">
                <input id="id_password" class="form-control" type="password" placeholder="Password" name="password">
              -->
                <input class="btn btn-default btn-login" type="button" value="Sign In" onclick="loginAjax()">
              </form>

            </div>
          </div>
        </div>
        <div class="box">
          <div class="content registerBox" style="display:none;">
           <div class="form">
            <form id="modal-register-form" method="post" html="{:multipart=>true}" data-remote="true" action="" accept-charset="UTF-8">              
              
              {% for hidden in reg_form.hidden_fields %}
                  {{ hidden }}
              {% endfor %}

              <div class="has-error" id="name-error-div"></div>
                {% with field=reg_form.name|add_class:'form-control' %}
                  {{ field|add_placeholder:'Name' }}
                {% endwith %}

              <div class="has-error" id="email-error-div"></div>
                {% with field=reg_form.email|add_class:'form-control' %}
                  {{ field|add_placeholder:'Email' }}
                {% endwith %}

              <div class="has-error" id="phone-error-div"></div>
                {% with field=reg_form.phone|add_class:'form-control' %}
                  {{ field|add_placeholder:'Phone Number' }}
                {% endwith %}

              <div class="has-error" id="password1-error-div"></div>
                {% with field=reg_form.password1|add_class:'form-control' %}
                  {{ field|add_placeholder:'Password' }}
                {% endwith %}

              <div class="has-error" id="password2-error-div"></div>
                {% with field=reg_form.password2|add_class:'form-control' %}
                  {{ field|add_placeholder:'Repeat Password' }}
                {% endwith %}

              {% csrf_token %}

              <input class="btn btn-default btn-register" type="submit" value="Create account" name="commit">
            <!--
              <input id="id_name" class="form-control" type="text" placeholder="Name" name="name">
              <input id="id_email" class="form-control" type="text" placeholder="Email" name="email">
              <input id="id_phone" class="form-control" type="text" placeholder="Phone Number" name="phone">
              <input id="id_password1" class="form-control" type="password" placeholder="Password" name="password">
              <input id="id_password2" class="form-control" type="password" placeholder="Repeat Password" name="password_confirmation">
            -->
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <div class="forgot login-footer">
        <span>Looking to 
         <a href="javascript: showRegisterForm();">create an account</a>
         ?</span>
       </div>
       <div class="forgot register-footer" style="display:none">
         <span>Already have an account?</span>
         <a href="javascript: showLoginForm();">Login</a>
       </div>
     </div>        
   </div>
 </div>
</div>
<!-- Login/Register modal -->

<link rel="stylesheet" type="text/css" href="{% static "css/login-modal.css" %}">
<script type="text/javascript" src="{% static "js/login-modal.js" %}"></script>

<script type="text/javascript">

    $('#modal-login-form').submit(function(e) {
      loginAjax();
      e.preventDefault();
    });

  $('#modal-register-form').submit(function(e) {
    registerAjax();
    e.preventDefault();
  });
</script>